services:
  govee2mqtt:
    container_name: govee2mqtt
    image: ghcr.io/wez/govee2mqtt:latest
    restart: always
    networks:
      - mqtt-net
    # Environment variables replace the need for an .env file
    environment:
      - GOVEE_MQTT_HOST=mosquitto
      - GOVEE_MQTT_PORT=1883
      - GOVEE_LAN_CONTROL=true

networks:
  mqtt-net:
    external: true