services:
  ring-mqtt:
    container_name: ring-mqtt
    image: tsightler/ring-mqtt:5.9.2
    restart: unless-stopped
    volumes:
      - /share/Container/ring-mqtt:/data
    environment:
      - MqttHost=localhsost
      - MqttPort=1883
    network_mode: host